# .github/workflows/validate-stack.yml
# CR-20251031-01: Assess Security Posture of Refactored ELK Stack Configuration
# CR-20251031-02: Verification of Security Control Remediation and Formal Closure of Assessment: Corrects command and adds secure environment variable handling.
# CR-20251031-03: Investigate and Remediate Failure of the 'Load environment variables' Step in CI/CD Pipeline: Removes the broken third-party action and uses the native '--env-file' flag.

name: Validate Docker Compose Stack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # CORRECTED STEP: We use the modern 'docker compose' command with the '--env-file' flag.
      # This tells Compose to load its variables directly from our non-secret .env.example file.
      # This removes the need for any third-party actions to manage environment variables.
      - name: Validate Docker Compose configuration
        run: docker compose --env-file .env.example config

      - name: Build the webapp service image
        run: docker compose --env-file .env.example build webapp

  secrets-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run Gitleaks secret scan
        uses: gitleaks/gitleaks-action@v2
