# .github/workflows/validate-stack.yml
# FINAL VERSION: Corrects command and adds secure environment variable handling.

name: Validate Docker Compose Stack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # This step uses the modern --env-file flag, which is simpler and avoids a third-party action.
      # It loads variables from the non-secret .env.example file for validation.
      - name: Validate Docker Compose configuration
        run: docker compose --env-file .env.example config

      - name: Build the webapp service image
        run: docker compose --env-file .env.example build webapp

  secrets-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run Gitleaks secret scan
        uses: gitleaks/gitleaks-action@v2
