name: Validate Docker Compose Stack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Security Gate 1: Validate docker-compose.yml syntax and variable substitution
      - name: Validate Docker Compose configuration
        run: docker-compose config

      # Security Gate 2: Build the webapp image to validate Dockerfile and requirements.txt
      - name: Build the webapp service image
        run: docker-compose build webapp

  secrets-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Gitleaks secret scan
        uses: gitleaks/gitleaks-action@v2
        with:
          args: --verbose
        # If you use a Gitleaks license, add it to repository secrets as GITLEAKS_LICENSE
